Repository JSD-0423/Frontend-Final-4, pull requests merged in 2023-07, with the labels that each got.

#2 creating file structure and installing mui
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: Awaiting Review

#3 edit app.jsx
  src/App.jsx
Labels: Awaiting Review

#8 Initial setup
  .eslintrc.cjs
  .prettierrc
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/Theme/index.jsx
  src/index.css
  src/main.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/NotFoundPage/NotFounPage.jsx
  src/shared/components/.gitkeep
Labels: Awaiting Review, requested-changes

#10 create axios instance
  .gitignore
  src/main.jsx
  src/services/ApiService.js
Labels: Approved

#11 landing page header
  src/App.jsx
  src/shared/components/.gitkeep
  src/shared/components/MobileUserMenu.jsx
  src/shared/components/NavMenu.jsx
  src/shared/components/Navbar.jsx
  src/shared/components/SearchBar.jsx
  src/shared/components/UserMenu.jsx
  src/shared/index.js
Labels: Awaiting Review, requested-changes

#13 landing page hero
  angular.png
  expressjs.webp
  src/pages/HomePage/HomePage.jsx
  src/shared/components/CustomCarousel.jsx
  src/shared/index.js
Labels: Approved

#14 New arrivals
  package-lock.json
  package.json
  public/assets/images/pink-bag-small 2.png
  public/assets/react.svg
  src/Theme/index.jsx
  src/pages/HomePage/HomePage.jsx
  src/shared/components/Carousel/Carousel.jsx
  src/shared/components/NewArrivals/NewArrivals.jsx
  src/shared/components/NewArrivals/NewArrivalsStyle.jsx
  src/shared/components/ProductCard/ProductCard.jsx
  src/shared/components/ProductCard/ProductCardStyle.jsx
  src/shared/components/ViewButton/ViewButton.jsx
  src/shared/components/ViewButton/ViewButtonStyle.jsx
Labels: Approved

#15 Handpicked collections & Shop by Brands
  src/Theme/index.jsx
  src/assets/images/BIBA.png
  src/assets/images/Chanel_logo.png
  src/assets/images/Dolce_&_Gabbana.png
  src/assets/images/H&M-Logo.png
  src/assets/images/Prada.png
  src/assets/images/Zara.png
  src/assets/images/handbags.png
  src/assets/images/personalCare.png
  src/assets/images/sunGlasses.png
  src/assets/images/wristwatches.png
  src/pages/HomePage/HomePage.jsx
  src/shared/components/IconCard/index.jsx
  src/shared/components/IconCard/style.jsx
  src/shared/components/ImageCard/index.jsx
  src/shared/components/ImageCard/style.jsx
  src/shared/components/ImageListBanner/index.jsx
  src/shared/components/ImageListBanner/style.jsx
Labels: Approved

#16 langing-page/new-arrivals/new-carousel
  package-lock.json
  package.json
  src/shared/components/Carousel/Carousel.jsx
  src/shared/components/CustomCarousel.jsx
  src/shared/components/ImageCard/index.jsx
  src/shared/components/ImageListBanner/index.jsx
  src/shared/components/NewArrivals/NewArrivalsStyle.jsx
  src/shared/components/ProductCard/ProductCardStyle.jsx
Labels: Awaiting Review

#20 implement UI design
  public/assets/images/BackGround.png
  src/Theme/index.jsx
  src/pages/HomePage/HomePage.jsx
  src/shared/components/Carousel/Carousel.jsx
  src/shared/components/ProductCard/ProductCard.jsx
  src/shared/components/ProductCard/ProductCardStyle.jsx
  src/shared/components/SpecialProductsBanner/SpecialProdcutBannerStyles.jsx
  src/shared/components/SpecialProductsBanner/SpecialProductBanner.jsx
Labels: Awaiting Review

#26 Landing page/15% discount
  public/assets/images/Group 139.png
  public/assets/images/pexels-anna-shvets-5217926 1.png
  public/assets/images/skincare 1.png
  src/Theme/index.jsx
  src/pages/HomePage/HomePage.jsx
  src/shared/components/CustomizedProducts/CustomizedProduct.jsx
  src/shared/components/CustomizedProducts/CustomizedProductStyles.jsx
  src/shared/components/CustomizedProductsBanner/CustomizedProductsBanner.jsx
  src/shared/components/CustomizedProductsBanner/CustomizedProductsBannerStyle.jsx
  src/shared/components/Footer/index.jsx
  src/shared/components/Footer/style.jsx
Labels: Awaiting Review

#27 landing page popular and discount UI
  src/shared/components/CustomizedProducts/CustomizedProductStyles.jsx
Labels: Awaiting Review

#29 fix deploy error
  src/shared/components/CustomizedProductsBanner/CustomizedProductsBanner.jsx
Labels: Awaiting Review

#32 creating the navigation for the mobile and updating the error message
  src/pages/CollectionsPage/components/ProductsContainer/ProductsContainer.jsx
  src/shared/components/ErrorMessage/ErrorMessage.jsx
  src/shared/components/NavMenu.jsx
  src/shared/index.js
Labels: Approved
